repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.0.1
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.4.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
